name: Automated Website Deployment upon Git Push

on:
  push:
    branches:
      - main

jobs:
  website-deployment:
    name: Execute Deployment Process
    runs-on: ubuntu-latest

    steps:
      - name: Retrieve Latest Source Code
        uses: actions/checkout@v2.3.2

      - name: Utilize Node.js v18
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Node Dependencies
        run: npm install

      - name: Synchronize Source Files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.ftp_server }}
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
